### PR TITLE
Update to rom 4.1

### PR DESCRIPTION
**Pull request by wafcio**
Based on rom-yaml which support ROM v4

### CODE REVIEW

**Comment by pmackay** [comment]
@wafcio hey, I know this is a couple of years old, but do you know why the various update PRs have not been merged? Would it make sense to merge this before attempting an upgrade to ROM 5.1?

**Comment by solnic** [comment]
@pmackay hey I missed it or didn't have time or some other reason :/ Anyhow, let's do this. I assume you need it now, right?

**Comment by pmackay** [comment]
@solnic I've setup a branch [here](https://github.com/pmackay/rom-csv/tree/update-to-rom-5) which forks from this PR and allows it to be used with ROM 5 and that seems to work for what I need (really like the approach BTW!). But it would be great to use the gem directly rather than a fork of a fork :-)

**Comment by solnic** [comment]
@pmackay OK please open a new PR that does the full upgrade to rom 5.0! I'll deal with the release process after your PR is merged.

**Pull request merged**
